name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Builds:
    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Installation of Typescript
      - run: npm install -g typescript 
      - name: Installing Required  Modules
      - run: yarn
      - name: Typescript Build
      - run: tsc
      - name: Remove @type Modules
      - run : npm uninstall -S @types/async && npm uninstall -S @types/fs-extra && npm uninstall -S @types/get-folder-size && npm uninstall -S @types/mime-types && npm uninstall -S @types/node && npm uninstall -S @types/node-telegram-bot-api && npm uninstall -S @types/tar && npm uninstall -S @types/uuid 
      - name: Compress Build Outputs
        run: |
          mkdir builds
          tar --exclude='./src' --exclude='./postinstall.mjs' --exclude='./builds' --exclude='./.git' --exclude='./downloads' --exclude='./.github' -cf builds/tar-bot.tar .
          tar --exclude='./src' --exclude='./postinstall.mjs' --exclude='./builds' --exclude='./.git' --exclude='./downloads' --exclude='./.github' -czf builds/tar-bot.tar.gz .
      - uses: actions/upload-artifact@v2
        with:
          name: Build Location Change
          path: builds/tar-bot.tar

      - run: |
          mv builds/tar-bot.tar tar-bot.tar
          mv builds/tar-bot.tar.gz tar-bot.tar.gz
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Build ${{ steps.get_version.outputs.VERSION }}
          files: |
            tar-bot.tar
            tar-bot.tar.gz
